### ISSUE TITLE
Challenges Implementing Polyfill - React/Vue

### ISSUE THREAD

**Issue by yaldram** [Marshal27/shadow-container-query-polyfill#38] opened 2023-01-17 07:12 UTC
- I am using this polyfill for supporting container queries on firefox. 
- But I see that the styles of my project break when using this plugin with firefox.
- I see that we have another additional element attached to the dom only on firefox this does not happen on other browsers.
<img width="411" alt="image" src="https://user-images.githubusercontent.com/13429535/212832872-210a06f3-20a9-487a-8945-53633b086467.png">

- I am using this polyfill with react. A fix will be appreciated. Thanks

**Comment by Marshal27** [comment] 2023-01-26 14:24
Would you be able to provide a `stackblitz` with a minimum reproduction of the issue?

Regarding the `cq-polyfill` element being attached, I imported the base version this repo was forked from [GoogleChromeLabs/container-query-polyfill](https://github.com/GoogleChromeLabs/container-query-polyfill) and it also creates the element you are referring to in firefox; that element was not introduced during the implementation of the Shadow Dom feature. 
> `DevKnoll` or some other contributor over there would need to speak to why it is necessary as I can only make assumptions.

If you are able to provide a `stackblitz` reproducing your issue, I can assist with troubleshooting any issues you may have and resolve them in the invent they are directly related to the introduction of the shadow dom feature.

**Comment by Marshal27** [comment] 2023-01-26 15:28
All browsers not supported are the ones where the element will show up.

https://caniuse.com/css-container-queries

**Comment by timsayshey** [comment] 2023-02-09 19:49
Hi @Marshal27 - I'm having the same issue. Do you have an example of this working with a web component on Stackblitz?

**Comment by Marshal27** [comment] 2023-02-09 19:59
@timsayshey reference the links in #33 

If you are able to provide me a minimum replication of your issue in `stackblitz` or `codesandbox`  I can take a look.

**Comment by Marshal27** [comment] 2023-02-09 21:24
@timsayshey here is a stackblitz example

https://stackblitz.com/edit/web-components-starter-p7sd4u?file=index.html

**Comment by timsayshey** [comment] 2023-02-09 21:27
Thanks! Yeah, the example works in Firefox. Then when I try to use the polyfill with my Vue web component, it doesn't work. I can see `cq-polyfill` being added. If I get time I'll try to reproduce it in Stackblitz.

**Comment by Marshal27** [comment] 2023-02-14 18:36
@timsayshey I am not terribly familiar with `vue`, but here is the hello world example replicated in a `vue` stackblitz.... I am working to get the webcomponent going now.

https://stackblitz.com/edit/vue-fuf4gs?file=src/App.vue

**Comment by Marshal27** [comment] 2023-02-14 19:04
@timsayshey I am not sure if I have the setup accurate for your situation, but, I do notice some odd behavior in that vue stackblitz. 

On initial load the polyfill does not work, but, if I modify the template in `App.vue` ... even just adding a blank carriage return in the template markup, the polyfill will start working. I don't know if this is a red herring created by this being in stackblitz or not, but, I do find this behavior interesting.

**Comment by timsayshey** [comment] 2023-02-14 19:05
Interesting. I wonder if the polyfill is running too early? Or does it poll for changes to the dom?

**Comment by Marshal27** [comment] 2023-02-14 19:08
The polyfill uses `MutationObserver` to detect dom changes, not sure about it being a race condition in the load, but anything is possible.

**Comment by Marshal27** [comment] 2023-02-14 19:10
In your local scenario, if you modify the template in the root `App.vue` does the polyfill begin working at all? I am trying to determine if the behavior I am seeing in this stackblitz example is related in any way to your scenario.

This may not even be a reasonable question/test scenario, just attempting to correlate this in anyway I can.

**Comment by timsayshey** [comment] 2023-02-14 22:04
Doesn't seem to be working. I just created a new Stackblitz example that creates a Vue Web Component and loads the polyfill. The container CSS works in Chrome of course, but not Firefox.

https://stackblitz.com/edit/vitejs-vite-yp6ndz?file=index.html,src%2FApp.vue,src%2FdefineCustomElementWithStyles.ts

**Comment by Marshal27** [comment] 2023-02-17 17:43
I think the key is to load the script sooner in your example; moving the script to the root `index.html` works. 

The polyfill should always be loaded as soon as possible, preferably in `index.html` if it is available, or via the `onMounted` approach if the `index.thml` is not available... Loading the polyfill from within the `customElement` is the issue here.

> notice in my example above there is no `indext.html` and is the reason I explored the `onMounted` approach in the root `App.vue`, but, that is exhibiting some odd behavior... if there is an `index.html` that is the way to go 100% of the time.

https://stackblitz.com/edit/vitejs-vite-saygfv?file=src/App.vue

**Comment by timsayshey** [comment] 2023-02-20 19:31
That's great @Marshal27 - What if I want to install the package from npm, how do I initiate it?

**Comment by Marshal27** [comment] 2023-02-21 19:36
- run `npm install --save shadow-container-query-polyfill` from the readme.
- remove `<script>` from index.html if it is still there.
- add import to the top of your `App.vue` file
  ```ts
  <script setup lang="ts">
  import { onMounted } from 'vue';
  import 'shadow-container-query-polyfill';
  ```
  
  **STACKBLITZ**

https://stackblitz.com/edit/vitejs-vite-saygfv?file=src/App.vue

**Comment by Marshal27** [comment] 2023-03-31 13:21
Closing due to no further activity.

**Closed as completed by Marshal27** 2023-03-31 13:21 UTC
